name: Test Telegram

on:
  workflow_dispatch:

jobs:
  send:
    runs-on: ubuntu-latest

    steps:
      - name: Send Telegram message
        run: |
          curl -X POST "https://${{secrets.VPS_IP}}:8084/api/message" \
            -H "Content-Type: application/json" \
            -H "X-Api-Key: AGENT_API_KEY" \
            -d '{
              "text": "что делает этот репозиторий?"
            }'
